pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
        }
        stage('Deploy in Staging Environment') {
            steps {
                build job: 'Deploy Application _staging _Env'
            }
        }
    }
    post {
        success {
            echo "Now Archiving the Artifacts...."
            archiveArtifacts artifacts: '*/.war'
        }
    }
}
